movie_server/movie_recommender/urls.py
from django.conf.urls import url

from . import views

app_name = 'movie_recommender'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^movie(?P<movie_id>[0-9]+)/$', views.movie, name='movie'),
    url(r'^user(?P<user_id>[0-9]+)/$', views.user, name='user'),
    url(r'^user_redirect/', views.user_redirect, name='user_redirect'),
    url(r'^movie_redirect/', views.movie_redirect, name='movie_redirect'),
    url(r'rate_movie/(?P<movie_id>[0-9]+)/$', views.rate_movie,
        name='rate_movie')
]

movie_server/movie_server/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from movie_recommender import views

urlpatterns = [
    url(r'^movie_recommender/', include('movie_recommender.urls')),
    url(r'^admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),
    url(r'^register/', views.register, name='register')
]

movie_server/movie_recommender/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg, Count


class Movie(models.Model):
    movie_id = models.IntegerField()
    title = models.CharField(max_length=200)

    def __str__(self):
        return "{}: {}".format(self.movie_id, self.title)

    def get_average_rating(self):
        movie_ratings = Rating.objects.filter(movie_id=self.id)
        movie_average = movie_ratings.aggregate(models.Avg('rating'))
        return movie_average['rating__avg']


class Rater(models.Model):
    sex_choices = (
        ('F', 'F'),
        ('M', 'M')
    )
    rater_id = models.IntegerField()
    age = models.IntegerField()
    sex = models.CharField(max_length=1, choices=sex_choices)
    occupation = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=5)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return "Rater ID: {}".format(self.user_id)


class Rating(models.Model):
    rating_choices = (
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5)
    )
    user_id = models.ForeignKey(Rater, on_delete=models.CASCADE)
    movie_id = models.ForeignKey(Movie, on_delete=models.CASCADE)
    rating = models.IntegerField(choices=rating_choices)

    def __str__(self):
        return "Movie {}: {}\nUser {} : Rating {}".format(
            self.movie_id.movie_id,
            self.movie_id.title,
            self.user_id.user_id,
            self.rating)

    @staticmethod
    def get_top_rated_movies(ratings_set, number_of_movies):
        pop_movies = ratings_set.annotate(
            count=Count('movie_id')).filter(count__gt=9)
        sorted_movies = pop_movies.values('movie_id').annotate(
            avg_rating=Avg('rating')).order_by('-avg_rating')
        tuple_list = [(x['movie_id'], x['avg_rating']) for x in sorted_movies]
        return tuple_list[:number_of_movies]

movie_server/movie_recommender/forms.py
from django import forms
from .models import Movie, Rater, Rating


class RaterForm(forms.ModelForm):
    age = forms.IntegerField(help_text="Please enter your age: ")
    sex = forms.ChoiceField(choices=Rater.sex_choices, help_text='Please enter your sex: ')
    occupation = forms.CharField(max_length=100, help_text='Please enter your occupation: ')
    zip_code = forms.CharField(max_length=5, help_text='Please enter your 5 digit zip/postal code: ')

    class Meta:
        model = Rater
        fields = ('age', 'sex', 'occupation', 'zip_code')


class RatingForm(forms.ModelForm):
    rating = forms.ChoiceField(choices=Rating.rating_choices, help_text='Please enter your rating: ')

    class Meta:
        model = Rating
        fields = ('rating', )

movie_server/movie_recommender/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from .models import Movie, Rater, Rating
from .forms import RaterForm, RatingForm


def index(request):
    all_ratings = Rating.objects.all()
    top_20_movies = Rating.get_top_rated_movies(all_ratings, 20)
    context = {'top_20_movies': top_20_movies}
    return render(request, 'movie_recommender/index.html', context)


def movie(request, movie_id):
    movie = Movie.objects.get(movie_id=movie_id)
    rating_list = Rating.objects.filter(movie_id=movie.id)
    rater_queries = rating_list.values_list('user_id', flat=True)
    movie_average = movie.get_average_rating
    context = {'movie': movie,
               'rating_list': rating_list,
               'average': movie_average,
               'rater_queries': rater_queries}
    return render(request, 'movie_recommender/movie.html', context)


def user(request, user_id):
    rater = Rater.objects.get(rater_id=user_id)
    rating_list = Rating.objects.filter(user_id=rater.id)
    page_user = User.objects.get(username='rater{}'.format(user_id))
    if request.user == page_user:
        seen_movies = rating_list.values_list(
            'movie_id', flat=True)
        unseen_ratings = Rating.objects.exclude(movie_id__in=seen_movies)
        top_20_movies = Rating.get_top_rated_movies(unseen_ratings, 20)
        context = {'top_20_movies': top_20_movies,
                   'rating_list': rating_list,
                   'rater': rater}
    else:
        context = {'rater': rater,
                   'rating_list': rating_list}
    return render(request, 'movie_recommender/user.html', context)


def register(request):
    new_id = Rater.objects.last().rater_id + 1
    if request.method == 'POST':
        form = RaterForm(request.POST)

        if form.is_valid():
            new_rater = form.save(commit=False)
            new_rater.rater_id = new_id
            new_user = User.objects.create_user(
                'rater{}'.format(new_id),
                'rater{}@here.com'.format(new_id),
                'rater{}password'.format(new_id))
            new_user.save()
            new_rater.user = new_user
            new_rater.save()
            user = authenticate(username=new_user.username,
                                password='rater{}password'.format(new_id))
            if user is not None:
                if user.is_active:
                    login(request, user)
            return user_redirect(request)
        else:
            print(form.errors)
    else:
        form = RaterForm()
    return render(request, 'registration/register.html', {'form': form})


def user_redirect(request):
    url = '/movie_recommender/user{}/'.format(request.user.rater.rater_id)
    return HttpResponseRedirect(url)


def movie_redirect(request, movie_id):
    url = '/movie_recommender/movie{}/'.format(movie_id)
    return HttpResponseRedirect(url)


def rate_movie(request, movie_id):
    if request.method == 'POST':
        form = RatingForm(request.POST)

        if form.is_valid():
            rating = form.save(commit=False)
            rating.movie_id = Movie.objects.get(movie_id=movie_id)
            rating.user_id = Rater.objects.get(
                rater_id=request.user.rater.rater_id)
            rating.save()
            return movie_redirect(request, movie_id)
        else:
            print(form.errors)
    else:
        # If the request was not a POST, display the form to enter details.
        form = RatingForm()
    movie_average = Movie.objects.get(movie_id=movie_id).get_average_rating()
    context = {'form': form,
               'movie': Movie.objects.get(movie_id=movie_id),
               'movie_average': movie_average}
    return render(request, 'movie_recommender/rate_movie.html', context)

movie_server/movie_recommender/templates/movie_recommender/index.html
{% if user.is_authenticated %}
{% with current_id=user.rater.rater_id %}
<p>Welcome, <a href="{% url 'movie_recommender:user' current_id %}">{{ user.username }}</a>. Thanks for logging in. <a href="{% url 'logout' %}">Log Out</a></p>
{% endwith %}
{% else %}
    <p>Welcome, new user. Please <a href="{% url 'login' %}">log in</a>.
    Or <a href="/register">register</a></p>
{% endif %}
<a href="{% url 'movie_recommender:index' %}">Home</a>
{% if top_20_movies %}
  <table>
    <tr>
      <th>Movie ID</th>
      <th>Average Rating</th>
    </tr>

    {% for movie, avg_rating in top_20_movies %}
      <tr>
        <td><b><a href="{% url 'movie_recommender:movie' movie %}">{{movie}}</a></b></td>
        <td>{{avg_rating}}</td>
      </tr>
    {% endfor %}
  </table>
{% endif %}

movie_server/movie_recommender/templates/movie_recommender/movie.html
{% if user.is_authenticated %}
    {% with current_id=user.rater.rater_id %}
    <p>Welcome, <a href="{% url 'movie_recommender:user' current_id %}">{{ user.username }}</a>. Thanks for logging in. <a href="{% url 'logout' %}">Log Out</a></p>
    {% endwith %}
    {% if user.rater.rater_id not in rater_queries %}
    <p>
        {% with flick_id=movie.movie_id %}
    <a href="{% url 'movie_recommender:rate_movie' flick_id %}">Rate {{movie.title}}</a>.
    {% endwith %}
    </p>
    {% endif %}
{% else %}
<p>Welcome, new user. Please <a href="{% url 'login' %}">log in</a>.
Or <a href="/register">register</a></p>
{% endif %}
<a href="{% url 'movie_recommender:index' %}">Home</a>
{% if movie %}
<p>
  <b>Title: </b>{{movie.title}}
  <b>Movie Id: </b>{{movie.movie_id}}
  <b>Average Rating: </b>{{average}}
</p>
    {% for rating in rating_list %}
        {% with person_id=rating.user_id_id %}
      <p>
        <a href="{% url 'movie_recommender:user' person_id %}">User: {{rating.user_id_id}}</a>
        <b>Rating: </b>{{rating.rating}}
      </p>
      {% endwith %}
    {% endfor %}
{% endif %}

movie_server/movie_recommender/templates/movie_recommender/rate_movie.html
<!DOCTYPE html>
<html>
    <head>
        <title>Add Rating</title>
    </head>

    <body>
        {% if user.is_authenticated %}
        {% with current_id=user.rater.rater_id %}
        <p>Welcome, <a href="{% url 'movie_recommender:user' current_id %}">{{ user.username }}</a>. Thanks for logging in. <a href="{% url 'logout' %}">Log Out</a></p>
        {% endwith %}
        {% else %}
            <p>Welcome, new user. Please <a href="{% url 'login' %}">log in</a>.</p>
        {% endif %}
        <a href="{% url 'movie_recommender:index' %}">Home</a>
        <h1>Add Rating</h1>
<p>
    Please add your rating for {{movie.title}}. Its average rating is: {{movie_average}}.
</p>
        <form id="RatingForm" method="post" action="">

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Add Rating" />
        </form>
    </body>

</html>

movie_server/movie_recommender/templates/movie_recommender/user.html
{% if user.is_authenticated %}
{% with current_id=user.rater.rater_id %}
<p>Welcome, <a href="{% url 'movie_recommender:user' current_id %}">{{ user.username }}</a>. Thanks for logging in. <a href="{% url 'logout' %}">Log Out</a></p>
{% endwith %}
{% else %}
<p>Welcome, new user. Please <a href="{% url 'login' %}">log in</a>.
Or <a href="/register">register</a></p>
{% endif %}
<a href="{% url 'movie_recommender:index' %}">Home</a>
{% if rater %}
<p>
  <b>User ID: </b>{{rater.rater_id}}
  <b>Age: </b>{{rater.age}}
  <b>Gender: </b>{{rater.sex}}
  <b>Occupation: </b> {{rater.occupation}}
</p>

{% if top_20_movies %}
<h2>Top 20 Unrated Movies</h2>
  <table>
    <tr>
      <th>Movie ID</th>
      <th>Average Rating</th>
    </tr>

    {% for movie, avg_rating in top_20_movies %}
      <tr>
        <td><b><a href="{% url 'movie_recommender:movie' movie %}">{{movie}}</a></b></td>
        <td>{{avg_rating}}</td>
      </tr>
    {% endfor %}
  </table>
{% endif %}
    {% for rating in rating_list %}
        {% with flick_id=rating.movie_id.movie_id %}
      <p>
        <a href="{% url 'movie_recommender:movie' flick_id%}">Movie: {{rating.movie_id.title}}</a>
        Movie ID: {{rating.movie_id.movie_id}}
        Rating: {{rating.rating}}

      </p>
        {% endwith %}
    {% endfor %}
{% endif %}